AWSTemplateFormatVersion: '2010-09-09'
Description: Create SNS topic and CloudWatch Alarm for EC2 CPU > threshold (email subscription requires confirmation)

Parameters:
  InstanceId:
    Type: String
    Description: EC2 InstanceId to monitor (e.g., i-0123456789abcdef0)
  EmailAddress:
    Type: String
    Description: Email to subscribe to SNS topic (user must confirm subscription)
  AlarmThreshold:
    Type: Number
    Default: 80

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ec2-cpu-alerts

  SNSTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: !Ref EmailAddress
      TopicArn: !Ref SNSTopic

  HighCpuAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "EC2-High-CPU-${InstanceId}"
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Dimensions:
        - Name: InstanceId
          Value: !Ref InstanceId
      Statistic: Average
      Period: 60
      EvaluationPeriods: 5
      Threshold: !Ref AlarmThreshold
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref SNSTopic
      TreatMissingData: notBreaching

Outputs:
  TopicArn:
    Value: !Ref SNSTopic
    Description: The SNS Topic ARN created
  AlarmName:
    Value: !Ref HighCpuAlarm
    Description: The CloudWatch Alarm name